"""A single self-contained HTML report for one run: the whole story on one shareable page.

Pure function of the RunResult, the linearizability verdict and the pre-rendered timeline
SVG -- no randomness, no I/O -- so the same run always produces byte-identical HTML (see
the golden-file test). Everything is inline (CSS + SVG), so the page opens standalone with
no external assets.
"""

from __future__ import annotations

import html

from .cluster import RunResult
from .linearizability import LinearizabilityResult
from .nemesis import NemesisSchedule

_CSS = """
body{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:24px;
color:#1a1a1a;background:#fafafa}
h1{font-size:20px;margin:0 0 4px}h2{font-size:14px;margin:24px 0 8px;color:#555;
text-transform:uppercase;letter-spacing:.05em}
.sub{color:#777;margin:0 0 20px}
.grid{display:flex;flex-wrap:wrap;gap:10px}
.card{background:#fff;border:1px solid #e5e5e5;border-radius:8px;padding:12px 16px;min-width:120px}
.card .n{font-size:22px;font-weight:600}.card .l{color:#888;font-size:12px}
.verdict{display:inline-block;padding:6px 14px;border-radius:999px;font-weight:600}
.pass{background:#e6f4ea;color:#1e7e34}.fail{background:#fdecea;color:#c62828}
.tl{background:#fff;border:1px solid #e5e5e5;border-radius:8px;padding:12px;overflow:auto}
table{border-collapse:collapse;background:#fff;border:1px solid #e5e5e5;border-radius:8px}
td,th{padding:6px 12px;border-bottom:1px solid #f0f0f0;text-align:right;
font-variant-numeric:tabular-nums}
th{color:#888;font-weight:500}td:first-child,th:first-child{text-align:left}
code{background:#f0f0f0;padding:2px 6px;border-radius:4px;font-size:13px}
.foot{color:#aaa;font-size:12px;margin-top:28px}
"""


def _card(value: object, label: str) -> str:
    return f'<div class="card"><div class="n">{value}</div><div class="l">{label}</div></div>'


def render_report(
    result: RunResult, verdict: LinearizabilityResult, timeline_svg: str,
    membership: bool = False, nemesis: NemesisSchedule | None = None,
) -> str:
    """Render one run as a standalone HTML page. ``membership``/``nemesis`` describe how
    the run was configured (RunResult does not carry them) so the footer's replay command
    reproduces THIS run, flags and all -- not a fault-free lookalike."""
    s = result.stats
    replay = (f"deterministic_raft replay --nodes {result.num_nodes} --seed {result.seed}\n"
              f"--faults {result.faults} --steps {result.steps}"
              + (" --membership" if membership else "")
              + (f" --nemesis '{nemesis.to_json()}'"
                 if nemesis is not None and nemesis.ops else ""))
    committed = max((n["commit_index"] for n in result.final), default=0)
    ok = verdict.linearizable
    verdict_html = (
        f'<span class="verdict {"pass" if ok else "fail"}">'
        f'{"LINEARIZABLE" if ok else "NOT LINEARIZABLE"}</span>'
        f'&nbsp;<span style="color:#777">{html.escape(verdict.message)}</span>'
    )

    cards = "".join([
        _card(f'{result.virtual_time}ms', "virtual time"),
        _card(result.steps, "steps"),
        _card(f'{s["leaders_elected"]}/{s["elections"]}', "leaders / elections"),
        _card(s["commands_submitted"], "commands"),
        _card(committed, "committed"),
        _card(verdict.checked_ops, "ops checked"),
    ])
    fault_cards = "".join([
        _card(s["partitions"], "partitions"),
        _card(s["crashes"], "crashes"),
        _card(s["dropped"], "messages dropped"),
        _card(s["duplicated"], "duplicated"),
        _card(s["retries"], "client retries"),
        _card(s["invariant_checks"], "invariant checks"),
    ])

    rows = "".join(
        f'<tr><td>n{n["id"]}</td><td>{"up" if n["alive"] else "down"}</td>'
        f'<td>{n["role"]}</td><td>{n["term"]}</td><td>{n["commit_index"]}</td>'
        f'<td>{n["applied"]}</td><td>{n["log_length"]}</td>'
        f'<td><code>{n["log_sha256"]}</code></td></tr>'
        for n in result.final
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>DeterministicRaft report - seed {result.seed}</title><style>{_CSS}</style></head>
<body>
<h1>DeterministicRaft run report</h1>
<p class="sub">{result.num_nodes} nodes &middot; seed {result.seed} &middot;
faults <code>{html.escape(result.faults)}</code> &middot; trace
<code>sha256:{result.digest[:16]}...</code></p>
<p>{verdict_html}</p>
<h2>Consensus</h2><div class="grid">{cards}</div>
<h2>Faults &amp; verification</h2><div class="grid">{fault_cards}</div>
<h2>Timeline</h2><div class="tl">{timeline_svg}</div>
<h2>Final node state</h2>
<table><tr><th>node</th><th>alive</th><th>role</th><th>term</th><th>commit</th>
<th>applied</th><th>log</th><th>log sha256</th></tr>{rows}</table>
<p class="foot">Generated by DeterministicRaft - Raft consensus verified by deterministic
simulation testing. Reproduce this run with
<code>{html.escape(replay)}</code>.</p>
</body></html>
"""
